In [2]:
import tensorflow as tf
import numpy as np

/Users/fionachow/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# TENSORS

Tensors can be stored in the graph as constants or variables - just operations.

Constants hold tensors whose values can't change, while variables hold tensors whose values can change.

Ref: https://developers.google.com/machine-learning/crash-course/exercises

In [3]:
sess = tf.InteractiveSession()

__Constants__

A constant is an operation that always returns the same tensor value.

In [4]:
c = tf.constant("Hello World")
sess.run(c)

b'Hello World'

__Variables__

A variable is an operation that will return whichever tensor has been assigned to it. When working with tf.Variables, you must explicitly initialize them by calling tf.global_variables_initializer at the start of your session.

In [13]:
v = tf.Variable([2])
initialization = tf.global_variables_initializer()

In [16]:
# Assemble a graph consisting of the following three operations:
#   * Two tf.constant operations to create the operands.
#   * One tf.add operation to add the two operands.
x = tf.constant(8, name="x_const")
y = tf.constant(5, name="y_const")
my_sum = tf.add(x, y, name="x_y_sum")

my_sum.eval()

13

__*Introduce a Third Operand*__

Define a third scalar integer constant, z, and assign it a value of 4.
Add z to my_sum to yield a new sum.

In [18]:
z = tf.constant(4, name='z_const')
third_op_sum = tf.add(my_sum, z, name='my_sum_z_new_sum')
third_op_sum.eval()

17

# Creating and Manipulating Tensors

In [19]:
# Create a six-element vector (1-D tensor).
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)

# Create another six-element vector. Each element in the vector will be
# initialized to 1. The first argument is the shape of the tensor (more
# on shapes below).
ones = tf.ones([6], dtype=tf.int32)

# Add the two vectors. The resulting tensor is a six-element vector.
just_beyond_primes = tf.add(primes, ones)

just_beyond_primes.eval()

array([ 3,  4,  6,  8, 12, 14], dtype=int32)

__*Tensor Shapes*__

Shapes are used to characterize the size and number of dimensions of a tensor. The shape of a tensor is expressed as list, with the ith element representing the size along dimension i. The length of the list then indicates the rank of the tensor (i.e., the number of dimensions).

In [20]:
# A scalar (0-D tensor).
scalar = tf.zeros([])

# A vector with 3 elements.
vector = tf.zeros([3])

# A matrix with 2 rows and 3 columns.
matrix = tf.zeros([2, 3])

print('scalar has shape', scalar.get_shape(), 'and value:\n', scalar.eval())
print('vector has shape', vector.get_shape(), 'and value:\n', vector.eval())
print('matrix has shape', matrix.get_shape(), 'and value:\n', matrix.eval())

scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [0. 0. 0.]
matrix has shape (2, 3) and value:
 [[0. 0. 0.]
 [0. 0. 0.]]


__Broadcasting__

In TensorFlow, operations can be performed on tensors that would traditionally have been incompatible.

TensorFlow supports broadcasting (a concept borrowed from numpy), where the smaller array in an element-wise operation is enlarged to have the same shape as the larger array.

In [22]:
# Create a six-element vector (1-D tensor).
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)

# Create a constant scalar with value 1.
ones = tf.constant(1, dtype=tf.int32)

# Add the two tensors. The resulting tensor is a six-element vector.
just_beyond_primes = tf.add(primes, ones)

just_beyond_primes.eval()

array([ 3,  4,  6,  8, 12, 14], dtype=int32)

__Matrix Multiplication__

In linear algebra, when multiplying two matrices, the number of columns of the first matrix must equal the number of rows in the second matrix.

It is valid to multiply a 3x4 matrix by a 4x2 matrix. This will result in a 3x2 matrix.

It is invalid to multiply a 4x2 matrix by a 3x4 matrix.

In [25]:
# Create a matrix (2-d tensor) with 3 rows and 4 columns.
x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
              dtype=tf.int32)

# Create a matrix with 4 rows and 2 columns.
y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)

# Multiply `x` by `y`. 
# The resulting matrix will have 3 rows and 2 columns.
matrix_multiply_result = tf.matmul(x, y)

print(matrix_multiply_result.eval())
print()
print(matrix_multiply_result.get_shape())

[[35 58]
 [35 33]
 [ 1 -4]]

(3, 2)


__Tensor Reshaping__

With tensor addition and matrix multiplication each imposing constraints on operands, TensorFlow programmers must frequently reshape tensors.

You can use the tf.reshape method to reshape a tensor. For example, you can reshape a 8x2 tensor into a 2x8 tensor or a 4x4 tensor:

In [29]:
# Create an 8x2 matrix (2-D tensor).
matrix = tf.constant([[1,2], [3,4], [5,6], [7,8],
                    [9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)

# Reshape the 8x2 matrix into a 2x8 matrix.
reshaped_2x8_matrix = tf.reshape(matrix, [2,8])

# Reshape the 8x2 matrix into a 4x4 matrix
reshaped_4x4_matrix = tf.reshape(matrix, [4,4])

print("Original matrix (8x2):")
print(matrix.eval())
print("Reshaped matrix (2x8):")
print(reshaped_2x8_matrix.eval())
print("Reshaped matrix (4x4):")
print(reshaped_4x4_matrix.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


You can also use tf.reshape to change the number of dimensions (the "rank") of the tensor. For example, you could reshape that 8x2 tensor into a 3-D 2x2x4 tensor or a 1-D 16-element tensor.

In [30]:
# Create an 8x2 matrix (2-D tensor).
matrix = tf.constant([[1,2], [3,4], [5,6], [7,8],
                    [9,10], [11,12], [13, 14], [15,16]], dtype=tf.int32)

# Reshape the 8x2 matrix into a 3-D 2x2x4 tensor.
reshaped_2x2x4_tensor = tf.reshape(matrix, [2,2,4])

# Reshape the 8x2 matrix into a 1-D 16-element tensor.
one_dimensional_vector = tf.reshape(matrix, [16])

print("Original matrix (8x2):")
print(matrix.eval())
print("Reshaped 3-D tensor (2x2x4):")
print(reshaped_2x2x4_tensor.eval())
print("1-D vector:")
print(one_dimensional_vector.eval())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped 3-D tensor (2x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
1-D vector:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


__EXERCISE: Reshape two tensors in order to multiply them.__

The following two vectors are incompatible for matrix multiplication:

a = tf.constant([5, 3, 2, 7, 1, 4])

b = tf.constant([4, 6, 3])

Reshape these vectors into compatible operands for matrix multiplication. Then, invoke a matrix multiplication operation on the reshaped tensors.

In [33]:
a = tf.constant([5, 3, 2, 7, 1, 4])

b = tf.constant([4, 6, 3])

reshaped_a_2X3_tensor = tf.reshape(a, [2, 3])
reshaped_b_3X1_tensor = tf.reshape(b, [3, 1])

reshaped_mul = tf.matmul(reshaped_a_2X3_tensor, reshaped_b_3X1_tensor)

reshaped_mul.eval()

array([[44],
       [46]], dtype=int32)

__Variables, Initialization and Assignment__

So far, all the operations we performed were on static values (tf.constant); calling eval() always returned the same result. TensorFlow allows you to define Variable objects, whose values can be changed.

When creating a variable, you can set an initial value explicitly, or you can use an initializer (like a distribution)

In [34]:
# Create a variable with the initial value 3.
v = tf.Variable([3])

# Create a variable of shape [1], with a random initial value,
# sampled from a normal distribution with mean 1 and standard deviation 0.35.
w = tf.Variable(tf.random_normal([1], mean=1.0, stddev=0.35))

One peculiarity of TensorFlow is that variable initialization is not automatic. eval() on Variable object will throw an exception.


The easiest way to initialize a variable is to call global_variables_initializer. Note the use of Session.run(), which is roughly equivalent to eval().

Once initialized, variables will maintain their value within the same session (however, when starting a new session, you will need to re-initialize them):

In [37]:
initialization = tf.global_variables_initializer()
sess.run(initialization)
# Now, variables can be accessed normally, and have values assigned to them.
print(v.eval())
print(w.eval())

[3]
[1.3576097]


To change the value of a variable, use the assign op. Note that simply creating the assign op will not have any effect. As with initialization, you have to run the assignment op to update the variable value:

In [38]:
sess.run(tf.global_variables_initializer())
# This should print the variable's initial value.
print(v.eval())

assignment = tf.assign(v, [7])
# The variable has not been changed yet!
print(v.eval())

# Execute the assignment op.
sess.run(assignment)
# Now the variable is updated.
print(v.eval())

[3]
[3]
[7]


__EXERCISE: Simulate 10 rolls of two dice.__
    
Create a dice simulation, which generates a 10x3 2-D tensor in which:

Columns 1 and 2 each hold one throw of one six-sided die (with values 1–6).
Column 3 holds the sum of Columns 1 and 2 on the same row.
For example, the first row might have the following values:

Column 1 holds 4

Column 2 holds 3

Column 3 holds 7

In [45]:
dice1 = tf.Variable(tf.random_uniform([10, 1],
                                        minval=1, maxval=7,
                                        dtype=tf.int32))
dice2 = tf.Variable(tf.random_uniform([10, 1],
                                        minval=1, maxval=7,
                                        dtype=tf.int32))
add_dice1_2 = tf.add(dice1, dice2)

dice_output = tf.concat([dice1, dice2, add_dice1_2], 1)
sess.run(tf.global_variables_initializer())
dice_output.eval()

array([[ 4,  2,  6],
       [ 6,  5, 11],
       [ 2,  6,  8],
       [ 2,  3,  5],
       [ 3,  1,  4],
       [ 3,  2,  5],
       [ 3,  6,  9],
       [ 2,  4,  6],
       [ 5,  4,  9],
       [ 5,  1,  6]], dtype=int32)