# TF - Tensor Transformations

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

/Users/fionachow/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Casting

Q1. Let X be a tensor of [["1.1", "2.2"], ["3.3", "4.4"]]. Convert the datatype of X to float32.

In [10]:
X = [["1.1", "2.2"], ["3.3", "4.4"]]
q1_tensor = tf.cast(tf.string_to_number(tf.convert_to_tensor(X)), dtype=tf.float32)

q1_tensor.eval()

array([[1.1, 2.2],
       [3.3, 4.4]], dtype=float32)

Q2. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float64.

In [12]:
X = np.array([[1, 2], [3, 4]]).astype(np.int32)
q2_tensor = tf.cast(tf.convert_to_tensor(X), dtype=tf.float64)

q2_tensor.eval()

array([[1., 2.],
       [3., 4.]])

Q3. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float32.

In [13]:
q3_tensor = tf.cast(tf.convert_to_tensor(X), dtype=tf.float32)

q3_tensor.eval()

array([[1., 2.],
       [3., 4.]], dtype=float32)

Q4. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int32.

In [14]:
X = np.array([[1, 2], [3, 4]]).astype(np.float32)

q4_tensor = tf.cast(tf.convert_to_tensor(X), dtype=tf.int32)

q4_tensor.eval()

array([[1, 2],
       [3, 4]], dtype=int32)

Q5. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int64.

In [15]:
X = np.array([[1, 2], [3, 4]]).astype(np.float32)

q5_tensor = tf.cast(tf.convert_to_tensor(X), dtype=tf.int64)

q5_tensor.eval()

array([[1, 2],
       [3, 4]])

## Shapes and Shaping

Q6. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the shape of X.

In [18]:
X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

q6_tensor = tf.constant(X.shape)

q6_tensor.eval()

array([3, 2, 2], dtype=int32)

Q7. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]) and y be a tensor [10, 20]. Create a list of tensors representing the shape of X and y.

In [21]:
X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
Y = np.array([10, 20])

out_X, out_y = tf.shape_n([X, Y]) 

out_X.eval(), out_y.eval()

(array([3, 2, 2], dtype=int32), array([2], dtype=int32))

Q8. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the size (=total number of elements) of X.

In [23]:
X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

tf.size(tf.constant(X)).eval()

12

Q9. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the rank (=number of dimensions) of X.

In [24]:
X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

tf.rank(tf.constant(X)).eval()

3

Q10. Let X be tf.ones([10, 10, 3]). Reshape X so that the size of the second dimension equals 150.

In [30]:
X = tf.ones([10, 10, 3])
xsize = tf.size(X).eval()
reshape_dim = (int(xsize/150), 150)

q10_tensor = tf.reshape(tensor=X, shape=reshape_dim)
q10_tensor.eval()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

Q11. Let X be tf.ones([10, 10, 1, 1]). Remove all the dimensions of size 1 in X.

In [34]:
X = tf.ones([10, 10, 1, 1])
q11_tensor =  tf.squeeze(X)
(q11_tensor.eval().shape)

(10, 10)

Q12. Let X be tf.ones([10, 10, 1, 1]). Remove only the third dimension in X.

In [35]:
X = tf.ones([10, 10, 1, 1])
q12_tensor = tf.squeeze(X, [-1])
q12_tensor.eval().shape

(10, 10, 1)

Q13. Let X be tf.ones([10, 10]). Add a dimension of 1 at the end of X.

In [37]:
X = tf.ones([10, 10])
q13_tensor = tf.expand_dims(input=X, dim=-1)
q13_tensor.eval().shape

(10, 10, 1)

## Slicing and Joining

Q14. Let X be a tensor<br/>
[[[1, 1, 1], [2, 2, 2]],<br/>
[[3, 3, 3], [4, 4, 4]],<br/>
[[5, 5, 5], [6, 6, 6]]].<br/>
Extract the [[[3, 3, 3], [5, 5, 5]] from X.

In [53]:
X = np.array([[[1, 1, 1], [2, 2, 2]],
[[3, 3, 3], [4, 4, 4]],
[[5, 5, 5], [6, 6, 6]]])

#num of rows, num of arrays each row, num of elements per array
print(X.shape)

q14_tensor = tf.slice(tf.convert_to_tensor(X), begin=(1, 0, 0), size=(2, 1, 3)) 
q14_tensor.eval()

(3, 2, 3)


array([[[3, 3, 3]],

       [[5, 5, 5]]])

Q15. Let X be a tensor of<br/>
[[ 1  2]<br />
 [ 3  4]<br />
 [ 5  6]<br />
 [ 7  8]<br />
 [ 9 10]].<br />
 Extract the [[1, 2], [5, 6], [9, 10]]] from X.

In [104]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
q15_tensor = tf.strided_slice(tf.convert_to_tensor(X),
                              begin=[0, 0],
                              end=[5, 5],
                              strides=[2, 1])

q15_tensor.eval()

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

Q16. Let X be a tensor of<br/>
[[ 1  2  3  4  5]<br />
 [ 6  7  8  9  10]].<br />
Split X into 5 same-sized tensors along the second dimension.

In [118]:
X = tf.convert_to_tensor(np.arange(1, 11).reshape(2, 5))
q16_tensor = tf.split(X, 5, axis=1)
[each.eval() for each in q16_tensor]

[array([[1],
        [6]]), array([[2],
        [7]]), array([[3],
        [8]]), array([[4],
        [9]]), array([[ 5],
        [10]])]

Q17. Lex X be a tensor<br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
Create a tensor looking like <br/>
[[ 1 2 3 1 2 3 1 2 3 ]<br/>
 [ 4 5 6 4 5 6 4 5 6 ]].

In [126]:
X = tf.convert_to_tensor(np.arange(1, 7).reshape(2, 3))
q17_tensor = tf.tile(X, multiples=[1, 3])
q17_tensor.eval()

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

Q18. Lex X be a tensor <br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
Pad 2 * 0's before the first dimension, 3 * 0's after the second dimension.

In [156]:
X = tf.convert_to_tensor(np.arange(1, 7).reshape(2, 3))

#[[num of row paddings before, row paddings after], [num of col paddings before, after]]
paddings = tf.constant([[2, 0], [0, 3]])
q18_tensor = tf.pad(X,
                   mode="CONSTANT",
                   paddings=paddings,
                   constant_values=0)
q18_tensor.eval()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 2, 3, 0, 0, 0],
       [4, 5, 6, 0, 0, 0]])

Q19. Lex X be a tensor <br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
and Y be a tensor<br/>
[[ 7 8 9]<br/>
 [10 11 12]].<br/>
Concatenate X and Y so that the new tensor looks like [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]].

In [157]:
X = tf.convert_to_tensor(np.arange(1, 7).reshape(2, 3))
Y = tf.convert_to_tensor(np.arange(7, 13).reshape(2, 3))
q19_tensor = tf.concat([X, Y], axis=1)
q19_tensor.eval()

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q20. Let x, y, and z be tensors [1, 4], [2, 5], and [3, 6], respectively. <br/>Create a single tensor from these such that it looks [[1, 2, 3], [4, 5, 6]].

In [166]:
X = tf.constant([1, 4])
Y = tf.constant([2, 5])
Z = tf.constant([3, 6])
#axis 1 combines by columns
q20_tensor = tf.stack([X, Y, Z], axis=1)
q20_tensor.eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

Q21. Let X be a tensor [[1, 2, 3], [4, 5, 6]]. Convert X into Y such that Y looks like [[1, 4], [2, 5], [3, 6]].

In [180]:
X = tf.convert_to_tensor(np.array([[1, 2, 3], [4, 5, 6]]))
#number of stacks, unstack by columns
unstacked_X = tf.unstack(X, num=3, axis=1)
q21_tensor = tf.parallel_stack(unstacked_X)
q21_tensor.eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

Q22. Given X below, reverse the sequence along the second axis except the zero-paddings. 

In [198]:
X = tf.constant(
[[[0, 0, 1],
  [0, 1, 0],
  [0, 0, 0]],
 
 [[0, 0, 1],
  [0, 1, 0],
  [1, 0, 0]]])

q22_tensor = tf.reverse_sequence(X, [2, 3], seq_axis=1, batch_axis=0)
print(q22_tensor.eval())

[[[0 1 0]
  [0 0 1]
  [0 0 0]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]]


Q23. Given X below, reverse the last dimension.

In [206]:
_X = np.arange(1, 1*2*3*4 + 1).reshape((1, 2, 3, 4))
X = tf.convert_to_tensor(_X)
q23_tensor = tf.reverse(
                        X,
                        axis=[-1])
q23_tensor.eval()

array([[[[ 4,  3,  2,  1],
         [ 8,  7,  6,  5],
         [12, 11, 10,  9]],

        [[16, 15, 14, 13],
         [20, 19, 18, 17],
         [24, 23, 22, 21]]]])

Q24. Given X below, permute its dimensions such that the new tensor has shape (3, 1, 2).

In [211]:
_X = np.ones((1, 2, 3))
X = tf.convert_to_tensor(_X)
q24_tensor = tf.transpose(X, perm=[2, 0, 1])
q24_tensor.eval().shape

(3, 1, 2)

Q25. Given X, below, get the first, and third rows.

In [216]:
_X = np.arange(1, 10).reshape((3, 3))
X = tf.convert_to_tensor(_X)
q25_tensor = tf.gather(
                        X,
                        [0, 2])
q25_tensor.eval()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [7, 8, 9]])

Q26. Given X below, get the elements 5 and 7.

In [223]:
_X = np.arange(1, 10).reshape((3, 3))
X = tf.convert_to_tensor(_X)
ind = [[[1, 1], [2,0]]]
q26_tensor = tf.gather_nd(X, ind)
q26_tensor.eval()

array([[5, 7]])

Q27. Let x be a tensor [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get the tensors of unique elements and their counts.

In [226]:
X = tf.convert_to_tensor(np.array([2, 2, 1, 5, 4, 5, 1, 2, 3]))
y, idx, count = tf.unique_with_counts(
                                    X,
                                    out_idx=tf.int32)
y.eval(), count.eval()

(array([2, 1, 5, 4, 3]), array([3, 2, 2, 1, 1], dtype=int32))

Q28. Let x be a tensor [1, 2, 3, 4, 5]. Divide the elements of x into a list of tensors that looks like [[3, 5], [1], [2, 4]].

In [227]:
X = tf.convert_to_tensor(np.array([1, 2, 3, 4, 5]))
partitions = [1, 2, 0, 2, 0]
q28_out = tf.dynamic_partition(
    data = X,
    partitions=partitions,
    num_partitions=3
)
[q.eval() for q in q28_out]

[array([3, 5]), array([1]), array([2, 4])]

Q29. Let X be a tensor [[7, 8], [5, 6]] and Y be a tensor [[1, 2], [3, 4]]. Create a single tensor looking like [[1, 2], [3, 4], [5, 6], [7, 8]].

In [229]:
X = tf.convert_to_tensor(np.array([[7, 8], [5, 6]]))
Y = tf.convert_to_tensor(np.array([[1, 2], [3, 4]]))
indice = [[3, 2],[0, 1]]
q29_tensor = tf.dynamic_stitch(indice, [X, Y])
q29_tensor.eval()

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Q30. Let x be a tensor [0, 1, 2, 3] and y be a tensor [True, False, False, True].<br/>
Apply mask y to x.

In [230]:
X = tf.convert_to_tensor(np.array([0, 1, 2, 3]))
Y = tf.constant([True, False, False, True])
q30_tensor = tf.boolean_mask(X, Y)
q30_tensor.eval()

array([0, 3])

Q31. Let x be a tensor [[0, 5, 3], [4, 2, 1]]. Convert X into one-hot.

In [238]:
X = tf.constant([[0, 5, 3], [4, 2, 1]])
q31_tensor = tf.one_hot(X, 6)
q31_tensor.eval()

array([[[1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.]]], dtype=float32)