# Control Flow

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

/Users/fionachow/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
author = "kyubyong. https://github.com/Kyubyong/tensorflow-exercises"

In [3]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Control Flow Operations

Q1. Let x and y be random 0-D tensors. Return x + y 
if x < y and x - y otherwise.

In [25]:
x = tf.constant(np.random.rand())
y = tf.convert_to_tensor(np.random.rand())

q1_tensor = tf.cond(x<y, lambda: tf.add(x, y), lambda: tf.subtract(x, y))
print(x.eval(), y.eval())
print(q1_tensor.eval())

0.4330062 0.7942757
1.2272819


Q2. Let x and y be 0-D int32 tensors randomly selected from 0 to 5. Return x + y 2 if x < y, x - y elif x > y, 0 otherwise.

In [33]:
x = tf.constant(np.random.randint(0, 5), dtype=np.int32)
y = tf.constant(np.random.randint(0, 5), dtype=np.int32)

print(x.eval(), y.eval())

default_const = tf.constant(0, dtype=np.int32)

q2_tensor = tf.case({tf.less(x, y): lambda: x+y,
                     tf.greater(x, y): lambda: x-y},
                    default=lambda: default_const, exclusive=True)

print(q2_tensor.eval())

1 0
1


Q3. Let X be a tensor [[-1, -2, -3], [0, 1, 2]] and Y be a tensor of zeros with the same shape as X. Return a boolean tensor that yields True if X equals Y elementwise.

In [44]:
X = tf.convert_to_tensor(np.array([[-1, -2, -3], [0, 1, 2]]), dtype=np.int32)
Y = tf.zeros(X.get_shape(), dtype=np.int32)
print(X.eval(), Y.eval())
q3_tensor = tf.equal(X, Y)
print(q3_tensor.eval())

[[-1 -2 -3]
 [ 0  1  2]] [[0 0 0]
 [0 0 0]]
[[False False False]
 [ True False False]]


## Logical Operators

Q4. Given x and y below, return the truth value x AND/OR/XOR y element-wise.

In [51]:
x = tf.constant([True, False, False], tf.bool)
y = tf.constant([True, True, False], tf.bool)
and_tensor = tf.logical_and(x, y)
or_tensor = tf.logical_or(x, y)
xor_tensor = tf.logical_xor(x, y)

q4_tensor = tf.stack([and_tensor, or_tensor, xor_tensor])
print(q4_tensor.eval())

[[ True False False]
 [ True  True False]
 [False  True False]]


Q5. Given x, return the truth value of NOT x element-wise.

In [52]:
x = tf.constant([True, False, False], tf.bool)

q5_tensor = tf.logical_not(x)
print(q5_tensor.eval())

[False  True  True]


## Comparison Operators

Q6. Let X be a tensor [[-1, -2, -3], [0, 1, 2]] and Y be a tensor of zeros with the same shape as x. Return a boolean tensor that yields True if X does not equal Y elementwise.

In [55]:
X = tf.convert_to_tensor(np.array([[-1, -2, -3], [0, 1, 2]]), dtype=np.int32)
Y = tf.zeros(X.get_shape(), dtype=np.int32)

q6_tensor = tf.equal(X, Y)
print(q6_tensor.eval())

[[False False False]
 [ True False False]]


Q7. Let X be a tensor [[-1, -2, -3], [0, 1, 2]] and Y be a tensor of zeros with the same shape as X. Return a boolean tensor that yields True if X is greater than or equal to Y elementwise.

In [56]:
X = tf.convert_to_tensor(np.array([[-1, -2, -3], [0, 1, 2]]), dtype=np.int32)
Y = tf.zeros(X.get_shape(), dtype=np.int32)

q7_tensor = tf.greater_equal(X, Y)
print(q7_tensor.eval())

[[False False False]
 [False  True  True]]


Q8. Let X be a tensor [[1, 2], [3, 4]], Y be a tensor [[5, 6], [7, 8]], and Z be a boolean tensor [[True, False], [False, True]]. Create a 2*2 tensor such that each element corresponds to X if Z is True, otherise Y.

In [60]:
X = tf.convert_to_tensor(np.array([[1, 2], [3, 4]]))
Y = tf.convert_to_tensor(np.array([[5, 6], [7, 8]]))
Z = tf.convert_to_tensor(np.array([[True, False], [False, True]]))

q8_tensor = tf.where(Z, X, Y)
print(q8_tensor.eval())

[[1 6]
 [7 4]]
