Author: https://github.com/Kyubyong/tensorflow-exercises

In [1]:
import tensorflow as tf
import numpy as np

/Users/fionachow/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sess = tf.InteractiveSession()

# Constants_Sequences_and_Random_Values

In [3]:
#Q1. Create a tensor of the shape [2, 3] with all elements set to zero.
q1_tensor = tf.zeros([2, 3])

print(q1_tensor.eval())

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#Q2. Let X be a tensor of [[1,2,3], [4,5,6]]. 
#Create a tensor of the same shape and dtype as X with all elements set to zero.
X = tf.constant([[1,2,3], [4,5,6]])
q2_tensor = tf.zeros(X.get_shape())

print(q2_tensor.eval())

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#Q3. Create a tensor of shape [2, 3] with all elements set to one.
q3_tensor = tf.ones([2, 3])

print(q3_tensor.eval())

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Q4. Let X be a tensor of [[1,2,3], [4,5,6]]. 
#Create a tensor of the same shape and dtype as X with all elements set to one.
q4_tensor = tf.ones(X.get_shape())

print(q4_tensor.eval())

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#SOLUTION
_X = np.array([[1,2,3], [4,5,6]])
X = tf.convert_to_tensor(_X)
out = tf.ones_like(X)
print(out.eval())

[[1 1 1]
 [1 1 1]]


In [7]:
#Q5. Create a tensor of the shape [3, 2], with all elements of 5.
q5_tensor = tf.constant(value=5, shape=[3, 2])

print(q5_tensor.eval())

[[5 5]
 [5 5]
 [5 5]]


In [23]:
#SOLUTION
out1 = tf.fill([3, 2], 5)
print(out1.eval())

[[5 5]
 [5 5]
 [5 5]]


In [9]:
#Q6. Create a constant tensor of [[1, 3, 5], [4, 6, 8]], with dtype=float32
q6_tensor = tf.constant([[1, 3, 5], [4, 6, 8]], dtype=np.float32)

print(q6_tensor.eval())

[[1. 3. 5.]
 [4. 6. 8.]]


In [10]:
#Q7. Create a constant tensor of the shape [2, 3], with all elements set to 4.
q7_tensor = tf.constant(value=4, shape=[2, 3])

print(q7_tensor.eval())

[[4 4 4]
 [4 4 4]]


# Sequences

In [14]:
#Q8. Create a 1-D tensor of 50 evenly spaced elements between 5 and 10 inclusive.
q8_tensor = tf.range(5, 10, delta=(11-5)/50, dtype=None, name='range')

print(q8_tensor.eval())

[5.        5.12      5.24      5.3599997 5.4799995 5.5999994 5.7199993
 5.839999  5.959999  6.079999  6.199999  6.3199987 6.4399986 6.5599985
 6.6799984 6.7999983 6.919998  7.039998  7.159998  7.279998  7.3999977
 7.5199976 7.6399975 7.7599974 7.8799973 7.999997  8.119997  8.239997
 8.359997  8.479997  8.599997  8.719996  8.839996  8.959996  9.079996
 9.199996  9.319996  9.439996  9.559996  9.679996  9.799995  9.919995 ]


In [24]:
#SOLUTION
out = tf.linspace(5., 10., 50)
print(out.eval())

[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ]


In [16]:
#Q9. Create a tensor which looks like [10, 12, 14, 16, ..., 100].
q9_tensor= tf.range(10, 101, 2)

print(q9_tensor.eval())

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


# Random Tensors

In [17]:
#Q10. Create a random tensor of the shape [3, 2],
#with elements from a normal distribution of mean=0, standard deviation=2.
q10_tensor = tf.random_normal(shape=[3, 2],
                              mean=0.0,
                              stddev=2.0,
                              dtype=tf.float32)

print(q10_tensor.eval())

[[-2.5838206   4.012572  ]
 [ 2.1589448   0.53605527]
 [-1.0143135  -1.3786379 ]]


In [18]:
#Q11. Create a random tensor of the shape [3, 2],
#with elements from a normal distribution of mean=0, standard deviation=1
#such that any values don't exceed 2 standard deviations from the mean.
q11_tensor = tf.random_normal(shape=[3, 2],
                              mean=0.0,
                              stddev=1.0,
                              dtype=tf.float32)

print(q11_tensor.eval())

[[-0.64378035 -0.27004606]
 [ 1.3157966  -0.32281837]
 [ 0.03965941 -0.68341583]]


In [25]:
#SOLUTION
out = tf.truncated_normal([3, 2])
print(out.eval())

[[ 0.5634254   1.0506076 ]
 [-0.7238139  -0.5294184 ]
 [ 0.03453378 -0.2676996 ]]


In [19]:
#Q12. Create a random tensor of the shape [3, 2],
#with all elements from a uniform distribution that ranges from 0 to 2 (exclusive).
q12_tensor = tf.random_uniform(
                                shape=[3, 2],
                                minval=0,
                                maxval=2,
                                dtype=tf.float32,
                            )

print(q12_tensor.eval())

[[1.7437418  1.6915004 ]
 [1.3894043  0.37233233]
 [0.34731174 0.231601  ]]


In [20]:
#Q13. Let X be a tensor of [[1, 2], [3, 4], [5, 6]].
#Shuffle X along its first dimension.
X = tf.constant([[1, 2], [3, 4], [5, 6]])

q13_tensor = tf.random_shuffle(X)

print(q13_tensor.eval())

[[1 2]
 [5 6]
 [3 4]]


In [21]:
#Q14. Let X be a random tensor of the shape [10, 10, 3],
#with elements from a unit normal distribution.
#Crop X with the shape of [5, 5, 3].
X = tf.random_normal(
    shape=[10, 10, 3],
    dtype=tf.float32
)

q14_tensor = tf.random_crop(X,
                            size=[5, 5, 3]
                           )

print(q14_tensor.eval())

[[[-0.2297542  -0.35578743 -1.5036045 ]
  [-0.20191051 -0.31680965 -0.7397404 ]
  [-0.66747123 -1.429316   -0.9081488 ]
  [-1.2430823  -1.2967135   1.37706   ]
  [-0.8806726   1.1837018  -0.8205752 ]]

 [[ 2.5796652   0.14420795  0.45152912]
  [ 1.0589567   1.5233465  -0.32812932]
  [-0.1081267  -0.2696964   0.08099049]
  [ 0.5669915  -0.5777837   0.42713055]
  [ 0.73541856 -0.04120554  0.05900655]]

 [[-0.3148139  -1.4084914   0.2820968 ]
  [-0.85088915  0.6115946   0.00506029]
  [-0.8395407   0.5706553  -0.22779284]
  [-0.9654998  -1.5894506  -0.24104767]
  [-1.9531943  -0.21741672  1.4337276 ]]

 [[ 1.854095    0.48075858  0.12202391]
  [-0.02125987  1.8063276   0.65060383]
  [ 0.7466592   0.30814737 -1.0596495 ]
  [ 0.77525467  0.3436308  -0.6493021 ]
  [-0.06687041 -1.2555549   3.1977897 ]]

 [[-2.0689075   0.5135881   0.5715283 ]
  [-0.50519764  0.39643407 -1.1111534 ]
  [-0.89940035  0.22556487 -0.57932717]
  [ 0.90384316 -0.9603264   0.2073884 ]
  [-0.07581397  0.26399618  0.36

# SOLUTION